GET http://localhost:3000/todos/
###

GET http://localhost:3000/todos/
###

GET http://localhost:3000/agenda/?date=2021-4-4

###
POST http://localhost:3000/todos/ 
Content-Type: application/json 

{
 "id": 18,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

### 

PUT http://localhost:3000/todos/5
Content-Type: application/json 

{ "dueDate": "2021-2-12" }

###
DELETE http://localhost:3000/todos/8
